package com.mycompany.myapp;


import DAO.AddDAO;
import Entities.User;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class guesthouse {

    private Form current;
    private static Form f;
    private Resources theme;
    public static User user=null;

    /**
     *
     */
    public static String localhost="https://guesthouse.000webhostapp.com/";
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return ;
        }
        f= new Form(BoxLayout.y());f.add(new Label(localhost));
        menus.setSearch(f);
        menus.addConnect(f);
        
        new AddDAO().getAds();
        f.show();
        
        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }

    }
    
    public void destroy() {
    }

    public static Form getF() {
        return f;
    }

    public static void setF(Form f) {
        guesthouse.f = f;
    }


    
}
