package GUI.Panels;

import GUI.GuestHouse;
import GUI.ViewAddAsOwner;
import GUI.home;
import GUI.viewAdd;
import entities.Add;
import entities.User;
import entitiesDao.HouseDAO;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author grami
 */
public class HousePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private final Add p;
    private home parent;

    public HousePanel(Add p, home u1) {
        this.p = p;
        parent = u1;

        initComponents();

        User u = new HouseDAO().findOwnerById(p.getId());
        owner.setText(u.getFirstName() + " " + u.getLastName());
        price.setText("" + p.getPrice());
        nature.setText(p.getNature());
        adress.setText(p.getCountry() + " " + p.getTown());
        starWars();
        System.out.println(p.getPicture1());

        if (p.getPicture1() != null) {

            pic.setIcon(new ImageIcon(p.getPicture1().getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH)));
        }
        for (Date d  : p.getDates()) {
            date.setText(date.getText()+d.toString()+" /");
            
        }

    }

    public void starWars() {

        if (p.getRating()
                > 4) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
        } else if (p.getRating()
                > 3) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
        } else if (p.getRating()
                > 2) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
        } else if (p.getRating()
                > 1) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
        } else if (p.getRating()
                > 0) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSelected.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        pic = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        owner = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        nature = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        viewAdd = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        pic.setBackground(new java.awt.Color(255, 255, 255));
        pic.setForeground(new java.awt.Color(255, 255, 255));
        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/houseicon.png"))); // NOI18N
        jToolBar1.add(pic);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("owner :");

        jLabel4.setText("adress :");

        jLabel5.setText("price :");

        jLabel6.setText("nature :");

        owner.setText("mr flen el fouleni");

        adress.setText("adress here");

        price.setText("xxxpt");

        nature.setText("house");

        date.setText("availiability  :");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        star1.setBackground(new java.awt.Color(255, 255, 255));
        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        star2.setBackground(new java.awt.Color(255, 255, 255));
        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        star3.setBackground(new java.awt.Color(255, 255, 255));
        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        star4.setBackground(new java.awt.Color(255, 255, 255));
        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        star5.setBackground(new java.awt.Color(255, 255, 255));
        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(star1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(star1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(star5)
                            .addComponent(star4)
                            .addComponent(star3)
                            .addComponent(star2))))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(owner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nature))
                            .addComponent(date)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adress)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(owner)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nature))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        viewAdd.setBackground(new java.awt.Color(153, 153, 153));
        viewAdd.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        viewAdd.setForeground(new java.awt.Color(51, 51, 51));
        viewAdd.setText("view Add");
        viewAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true));
        viewAdd.setFocusable(false);
        viewAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddActionPerformed(evt);
            }
        });
        jToolBar1.add(viewAdd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddActionPerformed
        if (GuestHouse.u == null) {
            new viewAdd(p).setVisible(true);
            parent.dispose();
        }else{
            GuestHouse.u.addAdds();
            if(GuestHouse.u.getAdds().contains(p)){
                new ViewAddAsOwner(p).setVisible(true);
                parent.dispose();
            }
            else{
                new viewAdd(p).setVisible(true);
            parent.dispose();
            }
            
        }
    }//GEN-LAST:event_viewAddActionPerformed

    public JButton getViewAdd() {
        return viewAdd;
    }

    public void setViewAdd(JButton viewAdd) {
        this.viewAdd = viewAdd;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adress;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel nature;
    private javax.swing.JLabel owner;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel price;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    private javax.swing.JButton viewAdd;
    // End of variables declaration//GEN-END:variables
}
