/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import GUI.Dialogs.deleteForum;
import GUI.Dialogs.updateForum;
import GUI.forum;
import GUI.myForums;
import entities.Forum;
import entitiesDao.ForumDAO;

public class myForum extends javax.swing.JPanel {

    ForumDAO fd;
    Forum f;

    private myForums p;

    public myForum(Forum f, myForums p) {
        this.p = p;
        this.f = f;
        initComponents();

        subject.setText(f.getSubject());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        subject = new javax.swing.JTextArea();
        updateB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        subject.setEditable(false);
        subject.setColumns(20);
        subject.setRows(5);
        subject.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(subject);

        jToolBar1.add(jScrollPane2);

        updateB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        updateB.setText("Update");
        updateB.setFocusable(false);
        updateB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBMouseClicked(evt);
            }
        });
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });
        jToolBar1.add(updateB);

        deleteB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        deleteB.setText("Delete");
        deleteB.setFocusable(false);
        deleteB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });
        jToolBar1.add(deleteB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        if (subject.isEditable()) {
            f.setSubject(subject.getText());
            updateForum u = new updateForum(p, true);
            u.setVisible(true);
            new ForumDAO().update(f);
            subject.setEditable(false);
        } else {
            subject.setEditable(true);
        }


    }//GEN-LAST:event_updateBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed

        deleteForum d = new deleteForum(p, true);
        d.setVisible(true);
        if (d.getReturnStatus() == 1) {
            fd = new ForumDAO();
            fd.removeById(f.getId());
            p.setMyForums();
        }

    }//GEN-LAST:event_deleteBActionPerformed

    private void subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectMouseClicked
        if (!subject.isEditable()) {
            forum ff = new forum(f);
            ff.setVisible(true);
            ff.setMessages();
            p.dispose();
        }
    }//GEN-LAST:event_subjectMouseClicked

    private void updateBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBMouseClicked


    }//GEN-LAST:event_updateBMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea subject;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
