/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Panels;

import GUI.GuestHouse;
import GUI.forum;
import GUI.myForums;
import Jobs.OldDiscussions;
import entities.Forum;
import entities.Message;
import entities.User;
import entitiesDao.MessageDAO;
import java.util.Map;


public class OldDiscussion extends javax.swing.JPanel {

   private OldDiscussions od;
   private Forum f;
   private User u;
   private myForums p;
   
    public OldDiscussion(Forum f,User u,myForums p) {
        this.p= p;
        this.u=u;    
        this.f=f;
        initComponents();
        od=new OldDiscussions(u);
        oldD.setText(f.getSubject());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        oldD = new javax.swing.JTextArea();
        unfollow = new javax.swing.JButton();

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        oldD.setEditable(false);
        oldD.setColumns(20);
        oldD.setRows(5);
        oldD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 255, 255), null, null));
        oldD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldDMouseClicked(evt);
            }
        });
        jToolBar1.add(oldD);

        unfollow.setBackground(new java.awt.Color(255, 255, 255));
        unfollow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unfollow.png"))); // NOI18N
        unfollow.setText("Unfollow");
        unfollow.setFocusable(false);
        unfollow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unfollow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        unfollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfollowActionPerformed(evt);
            }
        });
        jToolBar1.add(unfollow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void unfollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfollowActionPerformed
        
        f.setMessages();
        for (Map.Entry<Message, User> en : f.getMessages().entrySet()) {
            Message m = en.getKey();
            User k = en.getValue();
            
            if(k.equals(u))
                new MessageDAO().removeById(m.getId());
        }
        
        p.setOldDiscussions();
       
        
    }//GEN-LAST:event_unfollowActionPerformed

    private void oldDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldDMouseClicked

       forum ff= new forum(f);
      ff.setVisible(true);
      ff.setMessages();
       p.dispose();
    }//GEN-LAST:event_oldDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea oldD;
    private javax.swing.JButton unfollow;
    // End of variables declaration//GEN-END:variables
}
