/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Dialogs;

import GUI.GuestHouse;
import GUI.Panels.availableDate;
import entities.Add;
import entities.User;
import entitiesDao.AddDAO;
import entitiesDao.StayDAO;
import entitiesDao.UserDAO;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Mohamed
 */
public class finishTheReservation extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    private Add a;
    private User u;
    private Set<Date> dates;
    private Set<Date> ad;

    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form finishTheReservation
     */
    private GuestHouse parent;

    public finishTheReservation(GuestHouse parent, boolean modal, Add a) {

        super(parent, modal);
        this.parent = parent;
        initComponents();
        dates = new TreeSet<>();
        ad = new TreeSet<>();
        ad = a.getDates();
        this.a = a;
        this.u = GuestHouse.u;
        System.out.println(a);

        youHaveOnly.setVisible(false);
        userPoints.setVisible(false);

        System.out.println(u.getPoints());
     
        setAvailableDates();
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    public void addDate(Date d) {

        dates.add(d);
        setAvailableDates();
    }

    public void deleteDate(Date d) {
        dates.remove(d);
        setAvailableDates();
    }

    public Set<Date> getDates() {
        return dates;
    }

    public void setAvailableDates() {
        datesDispo.removeAll();

        

            for (Date d : ad) {

                if (dates.contains(d)) {
                    datesDispo.add(new availableDate(this, d, true));
                } else {
                    datesDispo.add(new availableDate(this, d, false));
                }

            }

            datesDispo.updateUI();
            datesDispo.repaint();

            cost.setText("" + (dates.size() * a.getPrice()));

            if (Integer.parseInt(cost.getText()) > u.getPoints()) {
                youHaveOnly.setVisible(true);
                userPoints.setText("" + u.getPoints());
                userPoints.setVisible(true);
                point.setVisible(true);
                okButton.setEnabled(false);
                buyMore.setVisible(true);

            } else {
                youHaveOnly.setVisible(false);
                userPoints.setVisible(false);
                point.setVisible(false);
                okButton.setEnabled(true);
                buyMore.setVisible(false);

            }
        

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userPoints = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        youHaveOnly = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        point = new javax.swing.JLabel();
        buyMore = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        datesDispo = new javax.swing.JToolBar();

        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel4.setText("point.");

        okButton.setBackground(new java.awt.Color(255, 255, 255));
        okButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        okButton.setForeground(new java.awt.Color(51, 204, 0));
        okButton.setText("OK");
        okButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Available dates :");

        userPoints.setBackground(new java.awt.Color(255, 255, 255));
        userPoints.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N

        cost.setBackground(new java.awt.Color(255, 255, 255));
        cost.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N

        youHaveOnly.setBackground(new java.awt.Color(255, 255, 255));
        youHaveOnly.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        youHaveOnly.setForeground(new java.awt.Color(255, 0, 0));
        youHaveOnly.setText("Sorry ! you have only ");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel2.setText("This will cost you");

        point.setBackground(new java.awt.Color(255, 255, 255));
        point.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        point.setForeground(new java.awt.Color(255, 0, 0));
        point.setText("point.");

        buyMore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buyMore.setForeground(new java.awt.Color(0, 0, 204));
        buyMore.setText("Buy more?");
        buyMore.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buyMore.setBorderPainted(false);
        buyMore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        datesDispo.setBackground(new java.awt.Color(204, 204, 204));
        datesDispo.setFloatable(false);
        datesDispo.setOrientation(javax.swing.SwingConstants.VERTICAL);
        datesDispo.setRollover(true);
        jScrollPane2.setViewportView(datesDispo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(youHaveOnly, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(userPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(point, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(buyMore)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(point)
                                    .addComponent(buyMore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(youHaveOnly))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        finalizeHostingDemand fhd = new finalizeHostingDemand(parent, true);
        fhd.setVisible(true);

        if (fhd.getReturnStatus() == 1) {

            UserDAO udao = new UserDAO();
            u.setPoints(u.getPoints() - Integer.parseInt(cost.getText()));
            udao.update(u);
            parent.resetPoints();
            AddDAO adao = new AddDAO();
            User owner;
            int ownerPoints;

            owner = adao.findOwnerById(a.getId());

            ownerPoints = owner.getPoints();
            owner.setPoints(ownerPoints + Integer.parseInt(cost.getText()));
            udao.update(owner);

            for (Date d : dates) {
                ad.remove(d);
            }
            adao.update(a);
            
            new StayDAO().add(a.getId(),u.getId());
            u.addStays();
            doClose(RET_OK);
        }


    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyMore;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cost;
    private javax.swing.JToolBar datesDispo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel point;
    private javax.swing.JLabel userPoints;
    private javax.swing.JLabel youHaveOnly;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
