/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Dialogs.logIn;
import GUI.Panels.HousePanel;
import Jobs.AddModel;
import GUI.Dialogs.web;
import entities.Add;
import entities.User;
import java.awt.Toolkit;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 *
 * @author grami
 */
public class home extends GuestHouse {

   
    private List<String> eql;
    private AddModel a;
    
  
    public home() {
        super();
        initComponents();
        
        a = new AddModel();
        eql = new ArrayList<>();      
        calendar.setMinSelectableDate( new Date(Calendar.getInstance().getTimeInMillis()));
        showAdds(a);
        if(u!=null)
            connect.setVisible(false);
        showAdds(a);
    }
    

    
    public void showAdds(AddModel a) {
        
        addsBar.removeAll();
        for (Add add : a.getAdds()) {
            addsBar.add(new HousePanel(add, this));
        }
        addsBar.updateUI();
        addsBar.repaint();
        System.out.println("done reloading ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        connect = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        country = new javax.swing.JComboBox<>();
        town = new javax.swing.JComboBox<>();
        SortSplit = new javax.swing.JSplitPane();
        SearchSplit = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        nature_equipment1 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        naturePanel3 = new javax.swing.JPanel();
        sortPrice = new javax.swing.JRadioButton();
        sortRating = new javax.swing.JRadioButton();
        sortEquipment = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        priceSlider = new javax.swing.JSlider();
        priceLabel = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        fiveStars = new javax.swing.JRadioButton();
        fourStars = new javax.swing.JRadioButton();
        threeStars = new javax.swing.JRadioButton();
        twoStars = new javax.swing.JRadioButton();
        oneStar = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jLabel10 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        addsBar = new javax.swing.JToolBar();
        jScrollPane5 = new javax.swing.JScrollPane();
        nature_equipment2 = new javax.swing.JToolBar();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        naturePanel2 = new javax.swing.JPanel();
        room2 = new javax.swing.JRadioButton();
        appartment2 = new javax.swing.JRadioButton();
        house2 = new javax.swing.JRadioButton();
        natureOther2 = new javax.swing.JRadioButton();
        natureOtherEntry2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        equipmentPanel2 = new javax.swing.JPanel();
        airConditioner2 = new javax.swing.JCheckBox();
        firePlace2 = new javax.swing.JCheckBox();
        washingMachine2 = new javax.swing.JCheckBox();
        dishWasher2 = new javax.swing.JCheckBox();
        dvd2 = new javax.swing.JCheckBox();
        indoorPool2 = new javax.swing.JCheckBox();
        sauna2 = new javax.swing.JCheckBox();
        jacuzzi2 = new javax.swing.JCheckBox();
        tv2 = new javax.swing.JCheckBox();
        elevator2 = new javax.swing.JCheckBox();
        barbecue2 = new javax.swing.JCheckBox();
        garden2 = new javax.swing.JCheckBox();
        gardenForniture2 = new javax.swing.JCheckBox();
        childrenGames2 = new javax.swing.JCheckBox();
        terrace2 = new javax.swing.JCheckBox();
        indoorParking2 = new javax.swing.JCheckBox();
        outdoorParking2 = new javax.swing.JCheckBox();
        equipmentOther2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        connect.setText("connect ?");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel2.setText("set up your destination please :");
        jToolBar2.add(jLabel2);

        country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunisia" }));
        country.setEnabled(false);
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        jToolBar2.add(country);

        town.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Soussa", "Monastir", "Mahdia", "Sfax", "Tunis", "Ben Arous", "Manouba", "Ariana", "Bizert", "Nabel", "Kef", "Gabes", "Mednine", "Tatawin", "Sidi Bou Zid", "Zaghouan", "Tozer", "Kairouan", "Beja", "Gasrine", "Gafsa", "Siliana", "Gbelli", "Jandouba" }));
        town.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townActionPerformed(evt);
            }
        });
        jToolBar2.add(town);

        SortSplit.setBorder(new javax.swing.border.MatteBorder(null));
        SortSplit.setDividerLocation(1100);

        SearchSplit.setDividerLocation(250);

        nature_equipment1.setFloatable(false);
        nature_equipment1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        nature_equipment1.setRollover(true);
        nature_equipment1.setEnabled(false);
        nature_equipment1.add(jSeparator4);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Sort");
        nature_equipment1.add(jLabel4);
        nature_equipment1.add(jSeparator13);

        buttonGroup2.add(sortPrice);
        sortPrice.setText("Price");
        sortPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortPriceActionPerformed(evt);
            }
        });

        buttonGroup2.add(sortRating);
        sortRating.setText("Rating");
        sortRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortRatingActionPerformed(evt);
            }
        });

        buttonGroup2.add(sortEquipment);
        sortEquipment.setText("equipments");
        sortEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortEquipmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout naturePanel3Layout = new javax.swing.GroupLayout(naturePanel3);
        naturePanel3.setLayout(naturePanel3Layout);
        naturePanel3Layout.setHorizontalGroup(
            naturePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naturePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(naturePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(naturePanel3Layout.createSequentialGroup()
                        .addGroup(naturePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortRating)
                            .addComponent(sortEquipment))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(naturePanel3Layout.createSequentialGroup()
                        .addComponent(sortPrice)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        naturePanel3Layout.setVerticalGroup(
            naturePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naturePanel3Layout.createSequentialGroup()
                .addComponent(sortPrice)
                .addGap(3, 3, 3)
                .addComponent(sortRating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortEquipment))
        );

        nature_equipment1.add(naturePanel3);
        nature_equipment1.add(jSeparator6);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Price");
        nature_equipment1.add(jLabel3);
        nature_equipment1.add(jSeparator14);

        priceSlider.setBackground(new java.awt.Color(0, 0, 0));
        priceSlider.setForeground(new java.awt.Color(0, 0, 255));
        priceSlider.setMaximum(1000);
        priceSlider.setMinorTickSpacing(5);
        priceSlider.setMaximumSize(new java.awt.Dimension(150, 26));
        priceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSliderStateChanged(evt);
            }
        });
        nature_equipment1.add(priceSlider);

        priceLabel.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 0, 0));
        priceLabel.setText("0 pt");
        priceLabel.setAlignmentY(0.0F);
        nature_equipment1.add(priceLabel);
        nature_equipment1.add(jSeparator12);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Rating");
        nature_equipment1.add(jLabel5);
        nature_equipment1.add(jSeparator15);

        buttonGroup3.add(fiveStars);
        fiveStars.setText("5");
        fiveStars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveStarsActionPerformed(evt);
            }
        });

        buttonGroup3.add(fourStars);
        fourStars.setText("4");
        fourStars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourStarsActionPerformed(evt);
            }
        });

        buttonGroup3.add(threeStars);
        threeStars.setText("3");
        threeStars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeStarsActionPerformed(evt);
            }
        });

        buttonGroup3.add(twoStars);
        twoStars.setText("2");
        twoStars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoStarsActionPerformed(evt);
            }
        });

        buttonGroup3.add(oneStar);
        oneStar.setText("1");
        oneStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneStarActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stars.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fiveStars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fourStars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(threeStars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twoStars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oneStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fiveStars, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourStars)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(threeStars)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(twoStars)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oneStar))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nature_equipment1.add(jPanel1);
        nature_equipment1.add(jSeparator9);

        jLabel10.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Date");
        nature_equipment1.add(jLabel10);

        calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarPropertyChange(evt);
            }
        });
        nature_equipment1.add(calendar);

        jScrollPane3.setViewportView(nature_equipment1);

        SearchSplit.setLeftComponent(jScrollPane3);

        addsBar.setBackground(new java.awt.Color(255, 255, 255));
        addsBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        addsBar.setFloatable(false);
        addsBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addsBar.setRollover(true);
        addsBar.setAutoscrolls(true);
        addsBar.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(addsBar);

        SearchSplit.setRightComponent(jScrollPane1);

        SortSplit.setLeftComponent(SearchSplit);

        nature_equipment2.setFloatable(false);
        nature_equipment2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        nature_equipment2.setRollover(true);
        nature_equipment2.add(jSeparator8);

        jLabel7.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Nature");
        nature_equipment2.add(jLabel7);
        nature_equipment2.add(jSeparator7);

        buttonGroup1.add(room2);
        room2.setText("room");
        room2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(appartment2);
        appartment2.setText("appartment");
        appartment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appartment2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(house2);
        house2.setText("house");
        house2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                house2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(natureOther2);
        natureOther2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natureOther2ActionPerformed(evt);
            }
        });

        natureOtherEntry2.setText("other..");
        natureOtherEntry2.setEnabled(false);
        natureOtherEntry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natureOtherEntry2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout naturePanel2Layout = new javax.swing.GroupLayout(naturePanel2);
        naturePanel2.setLayout(naturePanel2Layout);
        naturePanel2Layout.setHorizontalGroup(
            naturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naturePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(naturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(room2)
                    .addComponent(appartment2)
                    .addComponent(house2)
                    .addGroup(naturePanel2Layout.createSequentialGroup()
                        .addComponent(natureOther2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(natureOtherEntry2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        naturePanel2Layout.setVerticalGroup(
            naturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naturePanel2Layout.createSequentialGroup()
                .addComponent(room2)
                .addGap(3, 3, 3)
                .addComponent(appartment2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(house2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(naturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(natureOther2)
                    .addComponent(natureOtherEntry2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        nature_equipment2.add(naturePanel2);
        nature_equipment2.add(jSeparator3);

        jLabel8.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Equipments");
        nature_equipment2.add(jLabel8);

        equipmentPanel2.setAutoscrolls(true);

        airConditioner2.setText("Air Conditioner");
        airConditioner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airConditioner2ActionPerformed(evt);
            }
        });

        firePlace2.setText("fire place");
        firePlace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firePlace2ActionPerformed(evt);
            }
        });

        washingMachine2.setText("Washing Machine");
        washingMachine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washingMachine2ActionPerformed(evt);
            }
        });

        dishWasher2.setText("Dish Washer");
        dishWasher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishWasher2ActionPerformed(evt);
            }
        });

        dvd2.setText("DVD");
        dvd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvd2ActionPerformed(evt);
            }
        });

        indoorPool2.setText("Indoor Pool");
        indoorPool2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indoorPool2ActionPerformed(evt);
            }
        });

        sauna2.setText("Sauna");
        sauna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauna2ActionPerformed(evt);
            }
        });

        jacuzzi2.setText("Jacuzzi");
        jacuzzi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacuzzi2ActionPerformed(evt);
            }
        });

        tv2.setText("TV");
        tv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tv2ActionPerformed(evt);
            }
        });

        elevator2.setText("Elevator");
        elevator2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevator2ActionPerformed(evt);
            }
        });

        barbecue2.setText("Barbecue");
        barbecue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbecue2ActionPerformed(evt);
            }
        });

        garden2.setText("Garden");
        garden2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garden2ActionPerformed(evt);
            }
        });

        gardenForniture2.setText("Garden Fourniture");
        gardenForniture2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gardenForniture2ActionPerformed(evt);
            }
        });

        childrenGames2.setText("Children Games");
        childrenGames2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childrenGames2ActionPerformed(evt);
            }
        });

        terrace2.setText("Terrace");
        terrace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terrace2ActionPerformed(evt);
            }
        });

        indoorParking2.setText("Indoor Parking");

        outdoorParking2.setText("Outdoor Parking");
        outdoorParking2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outdoorParking2ActionPerformed(evt);
            }
        });

        equipmentOther2.setText("other...");
        equipmentOther2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentOther2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equipmentPanel2Layout = new javax.swing.GroupLayout(equipmentPanel2);
        equipmentPanel2.setLayout(equipmentPanel2Layout);
        equipmentPanel2Layout.setHorizontalGroup(
            equipmentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipmentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipmentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(airConditioner2)
                        .addComponent(firePlace2)
                        .addComponent(washingMachine2)
                        .addComponent(tv2)
                        .addComponent(elevator2)
                        .addComponent(barbecue2)
                        .addComponent(garden2)
                        .addComponent(gardenForniture2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(childrenGames2)
                        .addComponent(terrace2)
                        .addComponent(indoorParking2)
                        .addComponent(outdoorParking2)
                        .addComponent(equipmentOther2))
                    .addComponent(dishWasher2)
                    .addComponent(dvd2)
                    .addComponent(indoorPool2)
                    .addComponent(sauna2)
                    .addComponent(jacuzzi2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        equipmentPanel2Layout.setVerticalGroup(
            equipmentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(airConditioner2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firePlace2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(washingMachine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dishWasher2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dvd2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indoorPool2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sauna2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jacuzzi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tv2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elevator2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barbecue2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(garden2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gardenForniture2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childrenGames2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terrace2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indoorParking2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outdoorParking2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipmentOther2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(equipmentPanel2);

        nature_equipment2.add(jScrollPane6);

        jScrollPane5.setViewportView(nature_equipment2);

        SortSplit.setRightComponent(jScrollPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(SortSplit)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(SortSplit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        
        this.dispose();
        new logIn().setVisible(true);
        
    }//GEN-LAST:event_connectActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        

    }//GEN-LAST:event_countryActionPerformed

    private void townActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townActionPerformed
        
        a = new AddModel();
        
        a.findByTown((String) country.getSelectedItem(), (String) town.getSelectedItem());
        
        System.out.println(town.getSelectedItem());
        showAdds(a);
    }//GEN-LAST:event_townActionPerformed

    private void room2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room2ActionPerformed
        natureOtherEntry2.setText("other...");
        natureOtherEntry2.setEnabled(false);
        a = new AddModel();
        a.searchByNature("room");
        
        showAdds(a);
    }//GEN-LAST:event_room2ActionPerformed

    private void appartment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appartment2ActionPerformed
        natureOtherEntry2.setText("other...");
        natureOtherEntry2.setEnabled(false);
        a = new AddModel();
        a.searchByNature("appartment");
        showAdds(a);

    }//GEN-LAST:event_appartment2ActionPerformed

    private void house2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_house2ActionPerformed
        natureOtherEntry2.setText("other...");
        natureOtherEntry2.setEnabled(false);
        a = new AddModel();
        a.searchByNature("house");
        showAdds(a);

      }//GEN-LAST:event_house2ActionPerformed

    private void natureOther2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natureOther2ActionPerformed
        
        natureOtherEntry2.setText("");
        natureOtherEntry2.setEnabled(true);
        showAdds(a);
    }//GEN-LAST:event_natureOther2ActionPerformed

    private void airConditioner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airConditioner2ActionPerformed
        if (airConditioner2.isSelected()) {
            eql.add("airconditioner");
        } else {
            eql.remove("airconditioner");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_airConditioner2ActionPerformed

    private void indoorPool2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indoorPool2ActionPerformed
        if (indoorParking2.isSelected()) {
            eql.add("indoorpool");
        } else {
            eql.remove("indoorpool");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_indoorPool2ActionPerformed

    private void childrenGames2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childrenGames2ActionPerformed
        if (childrenGames2.isSelected()) {
            eql.add("childrengames");
        } else {
            eql.remove("childrengames");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_childrenGames2ActionPerformed

    private void outdoorParking2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outdoorParking2ActionPerformed
        if (outdoorParking2.isSelected()) {
            eql.add("outdoorparking");
        } else {
            eql.remove("outdoorparking");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_outdoorParking2ActionPerformed

    private void equipmentOther2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentOther2ActionPerformed
        a = new AddModel();
        a.findByOtherEquipment(equipmentOther2.getText());
        showAdds(a);
    }//GEN-LAST:event_equipmentOther2ActionPerformed

    private void sortEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortEquipmentActionPerformed
        a = new AddModel();
        a.SortByEquipments();
        showAdds(a);
        System.out.println("sorting by equipments");
    }//GEN-LAST:event_sortEquipmentActionPerformed

    private void sortRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortRatingActionPerformed
        a = new AddModel();
        this.a.SortByrating();
        showAdds(a);
        System.out.println("sorting by rating");
    }//GEN-LAST:event_sortRatingActionPerformed

    private void sortPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortPriceActionPerformed
        a = new AddModel();
        this.a.SortByPrice();
        showAdds(a);
        System.out.println("sorting by price");
    }//GEN-LAST:event_sortPriceActionPerformed

    private void fourStarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourStarsActionPerformed
        a = new AddModel();
        a.findByRating(3);
        showAdds(a);        // TODO add your handling code here:
    }//GEN-LAST:event_fourStarsActionPerformed

    private void threeStarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeStarsActionPerformed
        a = new AddModel();
        a.findByRating(2);
        showAdds(a);       // TODO add your handling code here:
    }//GEN-LAST:event_threeStarsActionPerformed

    private void twoStarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoStarsActionPerformed
        a = new AddModel();
        a.findByRating(1);
        showAdds(a);        // TODO add your handling code here:
    }//GEN-LAST:event_twoStarsActionPerformed

    private void oneStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneStarActionPerformed
        a = new AddModel();
        a.findByRating(0);
        showAdds(a);
    }//GEN-LAST:event_oneStarActionPerformed

    private void fiveStarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveStarsActionPerformed
        a = new AddModel();
        a.findByRating(4);
        showAdds(a);
    }//GEN-LAST:event_fiveStarsActionPerformed

    private void priceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceSliderStateChanged
        a = new AddModel();
        int x = priceSlider.getValue();
        a.setPriceMin(x);
        showAdds(a);
        priceLabel.setText("" + x + " pt");

    }//GEN-LAST:event_priceSliderStateChanged

    private void firePlace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firePlace2ActionPerformed
        // TODO add your handling code here:
        if (firePlace2.isSelected()) {
            eql.add("fireplace");
        } else {
            eql.remove("fireplace");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_firePlace2ActionPerformed

    private void washingMachine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washingMachine2ActionPerformed
        // TODO add your handling code here:
        if (washingMachine2.isSelected()) {
            eql.add("washingmachine");
        } else {
            eql.remove("washingmachine");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_washingMachine2ActionPerformed

    private void dishWasher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishWasher2ActionPerformed
        // TODO add your handling code here:
        if (dishWasher2.isSelected()) {
            eql.add("dishwasher");
        } else {
            eql.remove("dishwasher");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_dishWasher2ActionPerformed

    private void dvd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvd2ActionPerformed
        // TODO add your handling code here:
        if (dvd2.isSelected()) {
            eql.add("dvd");
        } else {
            eql.remove("dvd");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_dvd2ActionPerformed

    private void sauna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauna2ActionPerformed
        // TODO add your handling code here:
        if (sauna2.isSelected()) {
            eql.add("sauna");
        } else {
            eql.remove("sauna");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_sauna2ActionPerformed

    private void jacuzzi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacuzzi2ActionPerformed
        // TODO add your handling code here:
        if (jacuzzi2.isSelected()) {
            eql.add("jacuzzi");
        } else {
            eql.remove("jacuzzi");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_jacuzzi2ActionPerformed

    private void tv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tv2ActionPerformed
        // TODO add your handling code here:
        if (tv2.isSelected()) {
            eql.add("tv");
        } else {
            eql.remove("tv");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_tv2ActionPerformed

    private void elevator2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevator2ActionPerformed
        if (elevator2.isSelected()) {
            eql.add("elevator");
        } else {
            eql.remove("elevator");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_elevator2ActionPerformed

    private void barbecue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbecue2ActionPerformed
        // TODO add your handling code here:
        if (barbecue2.isSelected()) {
            eql.add("barbecue");
        } else {
            eql.remove("barbecue");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_barbecue2ActionPerformed

    private void garden2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garden2ActionPerformed
        // TODO add your handling code here:
        if (garden2.isSelected()) {
            eql.add("garden");
        } else {
            eql.remove("garden");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_garden2ActionPerformed

    private void gardenForniture2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gardenForniture2ActionPerformed
        if (gardenForniture2.isSelected()) {
            eql.add("gardenforniture");
        } else {
            eql.remove("gardenforniture");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_gardenForniture2ActionPerformed

    private void natureOtherEntry2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natureOtherEntry2ActionPerformed
        a = new AddModel();
        a.searchByNature(natureOtherEntry2.getText());
        showAdds(a);

    }//GEN-LAST:event_natureOtherEntry2ActionPerformed

    private void terrace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terrace2ActionPerformed
        if (terrace2.isSelected()) {
            eql.add("terrace");
        } else {
            eql.remove("terrace");
        }
        a = new AddModel();
        a.findByEquipments(eql);
        showAdds(a);
    }//GEN-LAST:event_terrace2ActionPerformed

    private void calendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarPropertyChange
        a = new AddModel();
        a.findByDate(new Date(calendar.getDate().getTime()));
        showAdds(a);
    }//GEN-LAST:event_calendarPropertyChange
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SearchSplit;
    private javax.swing.JSplitPane SortSplit;
    private javax.swing.JToolBar addsBar;
    private javax.swing.JCheckBox airConditioner2;
    private javax.swing.JRadioButton appartment2;
    private javax.swing.JCheckBox barbecue2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JCheckBox childrenGames2;
    private javax.swing.JButton connect;
    private javax.swing.JComboBox<String> country;
    private javax.swing.JCheckBox dishWasher2;
    private javax.swing.JCheckBox dvd2;
    private javax.swing.JCheckBox elevator2;
    private javax.swing.JTextField equipmentOther2;
    private javax.swing.JPanel equipmentPanel2;
    private javax.swing.JCheckBox firePlace2;
    private javax.swing.JRadioButton fiveStars;
    private javax.swing.JRadioButton fourStars;
    private javax.swing.JCheckBox garden2;
    private javax.swing.JCheckBox gardenForniture2;
    private javax.swing.JRadioButton house2;
    private javax.swing.JCheckBox indoorParking2;
    private javax.swing.JCheckBox indoorPool2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JCheckBox jacuzzi2;
    private javax.swing.JRadioButton natureOther2;
    private javax.swing.JTextField natureOtherEntry2;
    private javax.swing.JPanel naturePanel2;
    private javax.swing.JPanel naturePanel3;
    private javax.swing.JToolBar nature_equipment1;
    private javax.swing.JToolBar nature_equipment2;
    private javax.swing.JRadioButton oneStar;
    private javax.swing.JCheckBox outdoorParking2;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSlider priceSlider;
    private javax.swing.JRadioButton room2;
    private javax.swing.JCheckBox sauna2;
    private javax.swing.JRadioButton sortEquipment;
    private javax.swing.JRadioButton sortPrice;
    private javax.swing.JRadioButton sortRating;
    private javax.swing.JCheckBox terrace2;
    private javax.swing.JRadioButton threeStars;
    private javax.swing.JComboBox<String> town;
    private javax.swing.JCheckBox tv2;
    private javax.swing.JRadioButton twoStars;
    private javax.swing.JCheckBox washingMachine2;
    // End of variables declaration//GEN-END:variables
}
